### ISSUE TITLE
bot.on("update") method

### ISSUE THREAD

**Issue by AtakanErmis** [denogram/denogram#2]
There is a bot.on("update") method in Telegraf.js. Some examples:

`bot.on("new_chat_members", ctx => ctx.deleteMessage())`

this code removes "somebody Joined the group" notification when someone joins group. Another usage is:

`bot.on(["new_chat_members", "left_chat_member"], ctx => ctx.deleteMessage())`

this code waits for somebody to join or leave the group and when someone leave or join the group it removes the notification.

**Comment by stanislavstrelnikov** [comment]
resolved in https://github.com/denogram/denogram/commit/25765b07a1e3ac49902ea6eab981adc1edc9c1cf
