### ISSUE TITLE
bot.on should accept update type as a string

### ISSUE THREAD

**Issue by AtakanErmis** [denogram/denogram#4]
Telegraf.js accepts update type as a string. For example:

`bot.on("message", ctx => ctx.reply("hi"))`

**Comment by AtakanErmis** [comment]
I'l work on it.

**Comment by stanislavstrelnikov** [comment]
resolved in https://github.com/denogram/denogram/commit/99bef514b11ce31f28c6580199b656abc9f8dc4b
